// Generated by CoffeeScript 1.10.0
(function() {
  var report, roll, rollOne;

  module.exports = function(robot) {
    robot.respond(/roll (die|one)/i, function(msg) {
      return msg.reply(report([rollOne(6)]));
    });
    return robot.respond(/roll dice/i, function(msg) {
      return msg.reply(report(roll(2, 6)));
    });
  };

  report = function(results) {
    var finalComma, last, total;
    if (results != null) {
      switch (results.length) {
        case 0:
          return "I didn't roll any dice.";
        case 1:
          return "I rolled a " + results[0] + ".";
        default:
          total = results.reduce(function(x, y) {
            return x + y;
          });
          finalComma = results.length > 2 ? "," : "";
          last = results.pop();
          return "I rolled " + (results.join(", ")) + finalComma + " and " + last + ", totalling " + total + ".";
      }
    }
  };

  roll = function(dice, sides) {
    var i, j, ref, results1;
    results1 = [];
    for (i = j = 0, ref = dice; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      results1.push(rollOne(sides));
    }
    return results1;
  };

  rollOne = function(sides) {
    return 1 + Math.floor(Math.random() * sides);
  };

}).call(this);

//# sourceMappingURL=dice.js.map
// see if I need the map file
